name: gitallup
version: 0.2.0.0
github: gerdreiss/gitallup
license: BSD3
author: Gerd Reiss
maintainer: gerd@reiss.pro
copyright: 2020 Gerd Reiss

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on Github at <https://github.com/githubuser/gitallup#readme>

dependencies:
  - base >= 4.11 && < 10
  - rio >= 0.1.12.0
  - optparse-applicative
  - directory
  - filepath
  - bytestring
  - extra
  - split
  - pretty-simple

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  gitallup:
    main: Main.hs
    source-dirs: app
    dependencies:
      - gitallup
      - optparse-simple

    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
